group 'org.metafacture'
version '0.4.1'

apply plugin: 'java'

sourceCompatibility = 11
targetCompatibility = 11
compileJava.options.encoding = 'UTF-8'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'net.sf.saxon:Saxon-HE:9.8.0-10'
    implementation 'org.metafacture:metafacture-framework:5.0.0'
    testImplementation 'junit:junit:4.12'
    testImplementation 'org.mockito:mockito-core:2.5.5'
    testImplementation 'org.metafacture:metafacture-io:5.0.0'
}

task fatJar(type: Jar) {
    dependencies {
        implementation 'net.sf.saxon:Saxon-HE:9.8.0-10'
    }

    excludes = ['META-INF/SAXONICA.*', 'META-INF/maven/**', 'META-INF/services/**']

    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    archiveFileName = archivesBaseName.replace('-plugin', '') + '-' + version + '-plugin' + '.jar'
    with jar
}
